name: Build and deploy Flutter Web to Azure Web App - hexatracker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Web
        run: flutter build web --release

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: flutter-web
          path: build/web   # ← só envia a pasta buildada, não o projeto inteiro

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: flutter-web

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_FDD04A1B8EB74A12839875396E9DABAD }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_14E3E14CBA274AD4B65001CA6AE5B9BD }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6C00A64EAE4340AAAA2853DEDBA81BF7 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'hexatracker'
          slot-name: 'Production'
          package: .